version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies (if needed)
  build:
    commands:
      - echo Building the site (or skip if static)
  post_build:
    commands:
      - echo Deploying to S3
      - aws s3 sync . s3://my-store-site/ --delete

artifacts:
  files:
    - '**/*'
